import { ccuiDarkTheme, ccuiLightTheme, Theme } from '../theme';
import {
  ccuiCustomComponentsDarkThemeData,
  ccuiCustomComponentsDeepThemeData,
  ccuiCustomComponentsThemeData,
} from './theme-custom-components-data';
import { ccuiInitialThemeData } from './theme-initial-data';
export const infinityTheme: Theme = new Theme({
  id: 'infinity-theme',
  name: '无限主题',
  data: {
    ...ccuiLightTheme.data,
    ...ccuiInitialThemeData,
    ...ccuiCustomComponentsThemeData,
  },
  extends: 'ccui-light-theme',
  isDark: false,
});

export const provenceTheme: Theme = new Theme({
  id: 'provence-theme',
  name: '紫罗兰主题',
  data: {
    ...infinityTheme.data,
    'ccui-brand': '#7B69EE',
    'ccui-brand-foil': '#F5F5F9',
    'ccui-brand-active-focus': '#7B69EE',
    'ccui-primary-active': '#7B69EE',
    'ccui-brand-hover': '#7B69EE',
    'ccui-global-bg': '#f9fafb',
    'ccui-glass-morphism-bg': 'rgba(245, 246, 248,0.9)',
    'ccui-base-bg': '#ffffff',
    'ccui-text': '#070036',
    'ccui-aide-text': '#717087',
    'ccui-placeholder': '#babbc0',
    'ccui-disabled-text': '#cfd0d3',
    'ccui-disabled-bg': '#f5f5f6',
    'ccui-line': '#E2E2E5',
    'ccui-dividing-line': '#F2F2F3',
    'ccui-list-item-hover-bg': '#F5F5F9',
    'ccui-list-item-active-bg': '#7B69EE',
    'ccui-list-item-active-hover-bg': '#7B69EE',
    'ccui-list-item-selected-bg': '#F4F2FF',
    'ccui-list-item-hover-text': '#252b3a',
    'ccui-list-item-active-text': '#ffffff',
    'ccui-form-control-line': '#D7D8DA',
    'ccui-icon-text': '#babbc0',
    'ccui-brand-active': '#7B69EE',
    'ccui-primary': '#7B69EE',
    'ccui-primary-hover': '#7B69EE',
    'ccui-form-control-line-active': '#7B69EE',
    'ccui-form-control-interactive-outline': 'rgba(123,105,238,0.08)',
    'ccui-form-control-line-active-hover': '#7B69EE',
    'ccui-icon-fill-active': '#7B69EE',
    'ccui-icon-fill-active-hover': '#7B69EE',
    'ccui-label-bg': '#F4F2FF',
    'ccui-embed-search-bg': '#F4F2FF',
    'ccui-connected-overlay-line': '#7B69EE',
    'ccui-primary-disabled': '#d8d2fa',
    'ccui-icon-fill-active-disabled': '#d8d2fa',
    'ccui-link-active': '#3f1a9c',
    'ccui-gray-form-control-bg': '#f5f5f5',
    'ccui-gray-form-control-hover-bg': '#ebebeb',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const sweetTheme: Theme = new Theme({
  id: 'sweet-theme',
  name: '蜜糖主题',
  data: {
    ...infinityTheme.data,
    'ccui-brand': '#ec66ab',
    'ccui-brand-foil': '#f8f1f5',
    'ccui-brand-active-focus': '#ec66ab',
    'ccui-primary-active': '#ec66ab',
    'ccui-brand-hover': '#ec66ab',
    'ccui-global-bg': '#f9fafb',
    'ccui-glass-morphism-bg': 'rgba(245, 246, 248,0.9)',
    'ccui-base-bg': '#ffffff',
    'ccui-text': '#2f272f',
    'ccui-aide-text': '#827d82',
    'ccui-placeholder': '#bdb8bd',
    'ccui-disabled-text': '#cbcacb',
    'ccui-disabled-bg': '#f6f6f6',
    'ccui-line': '#aea6ad',
    'ccui-dividing-line': '#eae7e9',
    'ccui-list-item-hover-bg': '#f8f1f5',
    'ccui-list-item-active-bg': '#ffdcee',
    'ccui-list-item-active-hover-bg': '#ffdcee',
    'ccui-list-item-selected-bg': '#ffdcee',
    'ccui-list-item-hover-text': '#252b3a',
    'ccui-list-item-active-text': '#252b3a',
    'ccui-form-control-line': '#D7D8DA',
    'ccui-icon-text': '#babbc0',
    'ccui-brand-active': '#ec66ab',
    'ccui-primary': '#ec66ab',
    'ccui-primary-hover': '#ec66ab',
    'ccui-form-control-line-active': '#ec66ab',
    'ccui-form-control-interactive-outline': 'rgba(236,102,171,0.08)',
    'ccui-form-control-line-active-hover': '#ec66ab',
    'ccui-icon-fill-active': '#ec66ab',
    'ccui-icon-fill-active-hover': '#ec66ab',
    'ccui-label-bg': '#ffdcee',
    'ccui-embed-search-bg': '#ffdcee',
    'ccui-connected-overlay-line': '#ec66ab',
    'ccui-primary-disabled': '#fad1e6',
    'ccui-icon-fill-active-disabled': '#fad1e6',
    'ccui-link-active': '#96114d',
    'ccui-gray-form-control-bg': '#f5f5f5',
    'ccui-gray-form-control-hover-bg': '#ebebeb',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const deepTheme: Theme = new Theme({
  id: 'deep-theme',
  name: '深邃夜空主题',
  data: {
    ...infinityTheme.data,
    ...ccuiCustomComponentsDeepThemeData,
    'ccui-global-bg': '#F2F2F3',
    'ccui-glass-morphism-bg': 'rgba(242,242,243,0.9)',
    'ccui-base-bg': '#ffffff',
    'ccui-brand': '#252b3a',
    'ccui-brand-foil': '#f3f4f7',
    'ccui-brand-active-focus': '#252b3a',
    'ccui-primary-active': '#383e4d',
    'ccui-brand-active': '#252b3a',
    'ccui-brand-hover': '#252b3a',
    'ccui-text': '#252b3a',
    'ccui-aide-text': '#575d6c',
    'ccui-placeholder': '#9B9FA8',
    'ccui-disabled-text': '#9B9FA8',
    'ccui-disabled-bg': '#EBEBEB',
    'ccui-line': '#CFD0D3',
    'ccui-dividing-line': '#E2E2E6',
    'ccui-list-item-hover-bg': '#E2E2E6',
    'ccui-list-item-active-bg': '#d5d5db',
    'ccui-list-item-active-hover-bg': '#d5d5db',
    'ccui-list-item-selected-bg': '#d5d5db',
    'ccui-list-item-hover-text': '#252b3a',
    'ccui-list-item-active-text': '#252b3a',
    'ccui-icon-text': '#babbc0',
    'ccui-primary': '#252b3a',
    'ccui-primary-hover': '#575d6c',
    'ccui-form-control-line': '#CFD0D3',
    'ccui-form-control-line-hover': '#71757F',
    'ccui-icon-fill': '#575d6c',
    'ccui-icon-fill-weak': '#9B9FA8',
    'ccui-icon-fill-active': '#252B3A',
    'ccui-icon-fill-active-hover': '#252B3A',
    'ccui-shape-icon-fill': '#C7C7D1',
    'ccui-shape-icon-fill-hover': '#AEAEBD',
    'ccui-shape-icon-fill-active': '#AEAEBD',
    'ccui-shape-icon-fill-disabled': '#E0E0E0',
    'ccui-form-control-line-active': '#252b3a',
    'ccui-form-control-interactive-outline': 'rgba(37,43,58,0.08)',
    'ccui-form-control-line-active-hover': '#252b3a',
    'ccui-connected-overlay-line': '#252b3a',
    'ccui-primary-disabled': '#babbc0',
    'ccui-icon-fill-active-disabled': '#bebfc4',
    'ccui-gray-form-control-bg': '#f5f5f5',
    'ccui-gray-form-control-hover-bg': '#ebebeb',
    'ccui-nav-expand-bg': '#f7f7f8',
  },
  extends: 'infinity-theme',
  isDark: false,
});

export const galaxyTheme: Theme = new Theme({
  id: 'galaxy-theme',
  name: '追光主题',
  data: {
    ...ccuiDarkTheme.data,
    ...ccuiCustomComponentsDarkThemeData,
    'ccui-brand': '#526ECC',
    'ccui-info': '#526ECC',
    'ccui-primary': '#526ECC',
    'ccui-default-line': '#526ECC',
    'ccui-brand-hover': '#5E7CE0',
    'ccui-primary-hover': '#5E7CE0',
    'ccui-brand-foil': '#F2F2F3',
    'ccui-global-bg': '#1A1A1C',
    'ccui-glass-morphism-bg': 'rgba(26,26,28,0.9)',
    'ccui-base-bg': '#292A2E',
    'ccui-text': '#CED1DB',
    'ccui-aide-text': '#868A99',
    'ccui-placeholder': '#5B5D66',
    'ccui-disabled-text': '#5b5d66',
    'ccui-disabled-bg': '#2D2E32',
    'ccui-line': '#4e5057',
    'ccui-dividing-line': '#323438',
    'ccui-list-item-hover-bg': '#3d3d42',
    'ccui-list-item-active-bg': '#303548',
    'ccui-list-item-active-hover-bg': '#303548',
    'ccui-list-item-selected-bg': '#303548',
    'ccui-list-item-hover-text': '#F5F5F5',
    'ccui-list-item-active-text': '#4660B8',
    'ccui-primary-disabled': '#3f3f3f',
    'ccui-form-control-line': '#4e5057',
    'ccui-form-control-bg': '#292A2E',
    'ccui-form-control-line-hover': '#696c75',
    'ccui-form-control-line-active': '#526ECC',
    'ccui-form-control-interactive-outline': 'rgba(82,110,204,0.08)',
    'ccui-icon-text': '#868A99',
    'ccui-connected-overlay-bg': '#2E2F33',
    'ccui-fullscreen-overlay-bg': '#2E2F33',
    'ccui-warning-line': '#EB8F3D',
    'ccui-warning-bg': '#4b2e14',
    'ccui-success-line': '#2AA37E ',
    'ccui-success-bg': '#123d32',
    'ccui-danger-line': '#D15854',
    'ccui-danger-bg': '#4a2120',
    'ccui-info-line': '#4482BD',
    'ccui-info-bg': '#1c2543',
    'ccui-default-bg': '#313131',
    'ccui-label-bg': '#353537',
    'ccui-icon-fill': '#868A99',
    'ccui-icon-fill-hover': '#ced1db',
    'ccui-icon-fill-active': '#ced1db',
    'ccui-icon-fill-active-hover': '#ced1db',
    'ccui-border-radius': '4px',
    'ccui-border-radius-feedback': '4px',
    'ccui-border-radius-card': '8px',
    'ccui-font-size': '14px',
    'ccui-font-size-md': '14px',
    'ccui-font-size-card-title': '16px',
    'ccui-shadow-length-fullscreen-overlay': '0 0 6px 0',
    'ccui-gray-form-control-bg': '#323338',
    'ccui-gray-form-control-hover-bg': '#393A3E',
    'ccui-nav-expand-bg': '#1d1d21',
  },
  extends: 'ccui-dark-theme',
  isDark: true,
});
