export const ccuiInitialThemeData = {
  'ccui-global-bg': '#f6f6f8',
  'ccui-glass-morphism-bg': 'rgba(245, 246, 248, 0.9)',
  'ccui-global-bg-normal': '#ffffff',
  'ccui-base-bg': '#ffffff',
  'ccui-base-bg-dark': '#252b3a',
  'ccui-brand': '#5e7ce0',
  'ccui-brand-foil': '#f2f2f3',
  'ccui-brand-hover': '#7693f5',
  'ccui-brand-active': '#526ecc',
  'ccui-brand-active-focus': '#344899',
  'ccui-contrast': '#c7000b',
  'ccui-text': '#252b3a',
  'ccui-text-weak': '#575d6c',
  'ccui-aide-text': '#71757f',
  'ccui-aide-text-hover': '#252b3a',
  'ccui-aide-text-stress': '#575d6c',
  'ccui-placeholder': '#babbc0',
  'ccui-light-text': '#ffffff',
  'ccui-dark-text': '#252b3a',
  'ccui-link': '#526ecc',
  'ccui-link-active': '#526ecc',
  'ccui-link-light': '#96adfa',
  'ccui-link-light-active': '#beccfa',
  'ccui-line': '#d7d8da',
  'ccui-dividing-line': '#f2f2f3',
  'ccui-block': '#ffffff',
  'ccui-area': '#f5f5f5',
  'ccui-danger': '#f66f6a',
  'ccui-warning': '#fac20a',
  'ccui-waiting': '#beccfa',
  'ccui-success': '#50d4ab',
  'ccui-info': '#5e7ce0',
  'ccui-initial': '#e9edfa',
  'ccui-unavailable': '#f5f5f5',
  'ccui-shadow': 'rgba(37, 43, 58, 0.24)',
  'ccui-light-shadow': 'rgba(37, 43, 58, 0.12)',
  'ccui-connected-overlay-shadow': 'rgba(37, 43, 58, 0.16)',
  'ccui-feedback-overlay-shadow': 'rgba(37, 43, 58, 0.2)',
  'ccui-icon-text': '#71757f',
  'ccui-icon-bg': '#ffffff',
  'ccui-icon-fill': '#71757f',
  'ccui-icon-fill-weak': '#babbc0',
  'ccui-icon-fill-hover': '#252b3a',
  'ccui-icon-fill-active': '#252b3a',
  'ccui-icon-fill-active-hover': '#252b3a',
  'ccui-shape-icon-fill': '#d7d8da',
  'ccui-shape-icon-fill-hover': '#babbc0',
  'ccui-shape-icon-fill-active': '#babbc0',
  'ccui-shape-icon-fill-disabled': '#f5f5f5',
  'ccui-form-control-line': '#d7d8da',
  'ccui-form-control-bg': '#ffffff',
  'ccui-form-control-line-hover': '#9b9fa8',
  'ccui-form-control-line-active': '#5e7ce0',
  'ccui-form-control-interactive-outline': 'rgba(94,124,224,0.08)',
  'ccui-form-control-line-active-hover': '#344899',
  'ccui-list-item-active-bg': '#f2f5fc',
  'ccui-list-item-active-text': '#252b3a',
  'ccui-list-item-active-hover-bg': '#f2f5fc',
  'ccui-list-item-hover-bg': '#f2f2f3',
  'ccui-list-item-hover-text': '#252b3a',
  'ccui-list-item-selected-bg': '#f2f5fc',
  'ccui-list-item-strip-bg': '#f2f5fc',
  'ccui-disabled-bg': '#f5f5f5',
  'ccui-disabled-line': '#dfe1e6',
  'ccui-disabled-text': '#cfd0d3',
  'ccui-primary-disabled': '#beccfa',
  'ccui-icon-fill-active-disabled': '#beccfa',
  'ccui-label-bg': '#e9edfa',
  'ccui-connected-overlay-bg': '#ffffff',
  'ccui-connected-overlay-line': '#526ecc',
  'ccui-fullscreen-overlay-bg': '#ffffff',
  'ccui-feedback-overlay-bg': '#464d6e',
  'ccui-feedback-overlay-text': '#dfe1e6',
  'ccui-embed-search-bg': '#f2f2f3',
  'ccui-embed-search-bg-hover': '#eef0f5',
  'ccui-float-block-shadow': 'rgba(94, 124, 224, 0.3)',
  'ccui-highlight-overlay': 'rgba(255, 255, 255, 0.8)',
  'ccui-range-item-hover-bg': '#e9edfa',
  'ccui-gray-form-control-bg': '#f5f5f5',
  'ccui-gray-form-control-hover-bg': '#ebebeb',
  'ccui-nav-expand-bg': '#fbfbfc',
  'ccui-primary': '#5e7ce0',
  'ccui-primary-hover': '#7693f5',
  'ccui-primary-active': '#344899',
  'ccui-contrast-hover': '#d64a52',
  'ccui-contrast-active': '#b12220',
  'ccui-danger-line': '#f66f6a',
  'ccui-danger-bg': '#ffd5d4',
  'ccui-warning-line': '#fa9841',
  'ccui-warning-bg': '#ffe1c7',
  'ccui-info-line': '#5e7ce0',
  'ccui-info-bg': '#e9edfa',
  'ccui-success-line': '#50d4ab',
  'ccui-success-bg': '#cffcee',
  'ccui-primary-line': '#5e7ce0',
  'ccui-primary-bg': '#f2f5fc',
  'ccui-default-line': '#5e7ce0',
  'ccui-default-bg': '#f7f8fa',
  'ccui-shadow-length-base': '0 2px 6px 0',
  'ccui-shadow-length-slide-left': '-2px 0 8px 0',
  'ccui-shadow-length-slide-right': '2px 0 8px 0',
  'ccui-shadow-length-connected-overlay': '0 2px 12px 0',
  'ccui-shadow-length-hover': '0 4px 16px 0',
  'ccui-shadow-length-feedback-overlay': '0 8px 16px 0',
  'ccui-shadow-length-fullscreen-overlay': '0 10px 24px 0',
  'ccui-border-radius': '4px',
  'ccui-border-radius-feedback': '4px',
  'ccui-border-radius-card': '8px',
  'ccui-border-radius-full': '100px',
  'ccui-font-size': '14px',
  'ccui-font-size-card-title': '16px',
  'ccui-font-size-page-title': '16px',
  'ccui-font-size-modal-title': '18px',
  'ccui-font-size-price': '20px',
  'ccui-font-size-data-overview': '24px',
  'ccui-font-size-icon': '16px',
  'ccui-font-size-sm': '12px',
  'ccui-font-size-md': '14px',
  'ccui-font-size-lg': '14px',
  'ccui-font-title-weight': 'bold',
  'ccui-font-content-weight': 'normal',
  'ccui-line-height-base': '1.5',
  'ccui-animation-ease-in-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  'ccui-animation-duration-slow': '300ms',
  'ccui-animation-duration-base': '200ms',
  'ccui-animation-duration-fast': '100ms',
  'ccui-animation-ease-in': 'cubic-bezier(0.5, 0, 0.84, 0.25)',
  'ccui-animation-ease-out': 'cubic-bezier(0.16, 0.75, 0.5, 1)',
  'ccui-animation-ease-in-out': 'cubic-bezier(0.5, 0.05, 0.5, 0.95)',
  'ccui-animation-ease-in-out-smooth': 'cubic-bezier(0.645, 0.045, 0.355, 1)',
  'ccui-animation-linear': 'cubic-bezier(0, 0, 1, 1)',
  'ccui-z-index-full-page-overlay': '1080',
  'ccui-z-index-pop-up': '1060',
  'ccui-z-index-dropdown': '1052',
  'ccui-z-index-modal': '1050',
  'ccui-z-index-drawer': '1040',
  'ccui-z-index-framework': '1000'
};
